name: Build and commit
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium
      - name: Install node modules
        run: |-
          npm ci
      - name: Build wasm
        run: |-
          npx wasm-pack build -- --features js-api
        working-directory: ./star-trak
      - name: Build app
        run: |-
          npx ng build --prod --output-path docs --base-href /star-trak-pwa/
          cp docs/index.html docs/404.html
      - name: Commit and push to gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages-workdir
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -r docs
          cp -r ../docs .
          git add docs
          git commit -m "generated"
          git push
        working-directory: ./gh-pages-workdir
